[ERROR]: during executing: "openroad -exit -no_init -python /openlane/scripts/odbpy/io_place.py --config /openlane/designs/twos_complement/src/pin_order.cfg --hor-layer met3 --ver-layer met2 --ver-width-mult 2 --hor-width-mult 2 --hor-extension 0 --ver-extension 0 --length 4 --unmatched-error --input-lef /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/merged.nom.lef --output-def /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/4-io.def --output /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/4-io.odb /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/3-initial_fp.odb |& tee /dev/null /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/logs/floorplan/4-place_io.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
  File "/nix/store/k6rd3zzkbqzahl1bkyypqx8a6i2vg37q-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/odbpy/reader.py", line 89, in wrapper
    function(**kwargs)
  File "/openlane/scripts/odbpy/io_place.py", line 259, in io_place
    with open(config_file_name, "r") as config_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/openlane/designs/twos_complement/src/pin_order.cfg'
child process exited abnormally

[ERROR]: Step 4 (floorplan) failed with error:
-code 1 -level 0 -errorstack {INNER {invokeStk1 throw_error} CALL {try_exec openroad -exit -no_init -python /openlane/scripts/odbpy/io_place.py --config /openlane/designs/twos_complement/src/pin_order.cfg --hor-layer met3 --ver-layer met2 --ver-width-mult 2 --hor-width-mult 2 --hor-extension 0 --ver-extension 0 --length 4 --unmatched-error --input-lef /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/merged.nom.lef --output-def /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/4-io.def --output /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/4-io.odb /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/3-initial_fp.odb |& tee /dev/null /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/logs/floorplan/4-place_io.log} CALL {run_odbpy_script /openlane/scripts/odbpy/io_place.py --config /openlane/designs/twos_complement/src/pin_order.cfg --hor-layer met3 --ver-layer met2 --ver-width-mult 2 --hor-width-mult 2 --hor-extension 0 --ver-extension 0 --length 4 --unmatched-error --input-lef /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/merged.nom.lef --output-def /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/4-io.def --output /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/4-io.odb /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/3-initial_fp.odb |& tee /dev/null /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/logs/floorplan/4-place_io.log} CALL {manipulate_layout /openlane/scripts/odbpy/io_place.py -indexed_log /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/logs/floorplan/4-place_io.log -output_def /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/4-io.def -output /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/4-io.odb -input /openlane/designs/twos_complement/runs/RUN_2025.04.26_14.32.35/tmp/floorplan/3-initial_fp.odb --config /openlane/designs/twos_complement/src/pin_order.cfg --hor-layer met3 --ver-layer met2 --ver-width-mult 2 --hor-width-mult 2 --hor-extension 0 --ver-extension 0 --length 4 --unmatched-error} CALL place_io_ol CALL run_floorplan CALL {run_non_interactive_mode -design twos_complement -noclock}} -errorcode NONE -errorinfo {
    while executing
"throw_error"
    (procedure "try_exec" line 15)
    invoked from within
"try_exec $::env(OPENROAD_BIN) -exit -no_init -python {*}$args"
    (procedure "run_odbpy_script" line 3)
    invoked from within
"run_odbpy_script {*}$args  --input-lef $::env(MERGED_LEF)  --output-def $arg_values(-output_def)  --output $arg_values(-output)  $arg_values(-input)  ..."
    (procedure "manipulate_layout" line 19)
    invoked from within
"manipulate_layout $::env(SCRIPTS_DIR)/odbpy/io_place.py -indexed_log [index_file $::env(floorplan_logs)/place_io.log] -output_def $arg_values(-output_..."
    (procedure "place_io_ol" line 50)
    invoked from within
"place_io_ol"
    (procedure "run_floorplan" line 27)
    invoked from within
"run_floorplan"} -errorline 1
[ERROR]: Failed to create manufacturability and metric reports:
[ERROR]: Traceback (most recent call last):
  File "/openlane/scripts/generate_reports.py", line 184, in <module>
    cli()
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/generate_reports.py", line 51, in cli
    report = Report(design, tag, design_name, params, run_path).get_report()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 809, in get_report
    *self.extract_all_values(),
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 359, in extract_all_values
    power_report = Artifact(
                   ^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 62, in __init__
    self.pathname = matches[0]
                    ~~~~~~~^^^
IndexError: list index out of range
[ERROR]: Flow failed.
